doctrine_mongodb:
  connections:
    default:
      server: "mongodb://10.18.0.3:27017"
      options:
        username: ggm
        password: ggm
  default_database: test_database
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          type: annotation
          dir: '%kernel.project_dir%/src/Document'
          prefix: 'App\Document'
          alias: App